---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: rubabzahra/scd-final-lab-exam-rubabzahra13-client:latest
        ports:
        - containerPort: 53832

---
apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  selector:
    app: client
  ports:
    - protocol: TCP
      port: 53832
      targetPort: 53832

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: rubabzahra/scd-final-lab-exam-rubabzahra13-auth:latest
        ports:
        - containerPort: 55832
        env:
        - name: PORT
          value: "55832"

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 55832
      targetPort: 55832

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: classrooms-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: classrooms
  template:
    metadata:
      labels:
        app: classrooms
    spec:
      containers:
      - name: classrooms
        image: rubabzahra/scd-final-lab-exam-rubabzahra13-classrooms:latest
        ports:
        - containerPort: 55832

---
apiVersion: v1
kind: Service
metadata:
  name: classrooms-service
spec:
  selector:
    app: classrooms
  ports:
    - protocol: TCP
      port: 55832
      targetPort: 55832

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-bus-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-bus
  template:
    metadata:
      labels:
        app: event-bus
    spec:
      containers:
      - name: event-bus
        image: rubabzahra/scd-final-lab-exam-rubabzahra13-event-bus:latest
        ports:
        - containerPort: 55832

---
apiVersion: v1
kind: Service
metadata:
  name: event-bus-service
spec:
  selector:
    app: event-bus
  ports:
    - protocol: TCP
      port: 55832
      targetPort: 55832

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post
  template:
    metadata:
      labels:
        app: post
    spec:
      containers:
      - name: post
        image: rubabzahra/scd-final-lab-exam-rubabzahra13-post:latest
        ports:
        - containerPort: 55832

---
apiVersion: v1
kind: Service
metadata:
  name: post-service
spec:
  selector:
    app: post
  ports:
    - protocol: TCP
      port: 55832
      targetPort: 55832

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
        - containerPort: 27018
        volumeMounts:
        - mountPath: /data/db
          name: mongodb-data
  volumes:
    - name: mongodb-data
      emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017

---
